name: ephemeral_value
description: Ephemeral value types for Dart and Flutter. Easily represent loading, success, error, empty, and initial states in your app logic and UI.
version: 1.0.0
repository: https://github.com/xamantra/ephemeral_value
homepage: https://github.com/xamantra/ephemeral_value
issue_tracker: https://github.com/xamantra/ephemeral_value/issues

environment:
  sdk: ^3.2.6

topics:
  - state-management
  - value
  - loading
  - dart
  - flutter

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

# Add keywords for pub.dev search
keywords:
  - state
  - ephemeral
  - value
  - loading
  - error
  - empty
  - initial
  - success
  - dart
  - flutter